### PR TITLE
[WIP] LibInjection Module

### PR DESCRIPTION
**Pull request by buixor**
Hello,

This is a module that relies on [libinjection](https://github.com/client9/libinjection/) and [pylibinjection](https://pypi.org/project/pylibinjection/) in an attempt to improve the SQL injection detection rate.

I will test and improve the module once I get access to the feed, and notify you when/if I feel it's ready to merge.

In the meanwhile, feedback is welcome :)

Do you prefer a separate module, or this mechanism being integrated into the existing SQLInjectionDetection module ? (libinjection brings an extra dependence)

### CODE REVIEW

**Comment by mokaddem** [comment]
This is great! Thanks!
You are free to choose to integrate it directly into ``SQLInjectionDetection.py`` or leave it as it is.
Looking forward for more!

**Comment by adulau** [comment]
@mokaddem should we merge or make it optional?

**Comment by Terrtia** [comment]
Thank you !

**Comment by buixor** [comment]
Hello,

I didn't really had  time to test it with live data (hence the `[WIP]`), I hope this won't lead to any issues ...

**Pull request merged**
