### PR TITLE
Added module Regex.py

### PR DESCRIPTION
**Pull request by xme**
I created a module to search for regular expressions. 
Regexes are loaded from a configuration file and create specific tags.
Just let me know if you find it useful, comments are welcome!

### CODE REVIEW

**Comment by mokaddem** [comment]
Hello!
First of all, thanks for your contribution, it is much appreciated!
However, I'm wondering why you are not using the dedicated web interface (under ``Terms frequency->Terms managements``) to search for regexes.
Am I missing something a feature that your PR provide in addition to what already exists.
As far as I can see, the tagging of the matched element is missing from the code base but this could be quickly done by cherry picking from your code ;)

**Comment by xme** [comment]
True but as you said I like to have dedicated tags (ex: when hunting for customers' data). Also, the regex config file is re-read when updated. This helps me to automate the management of regexes. No worries if you reject the pull request ;-)

**Comment by mokaddem** [comment]
Having the term frequency adding tags when it matches is planned. Also these regexes are loaded as soon as they are added.
However, as some users may prefer to use config file rather than the web interface, we can merge it.

Before hand, could you please
- move the ``regex.cfg`` file into ``config/regex.cfg``
- Add a threshold in the script ``Regex.py`` (similarly to what's done in [RegexForTermsFrequency.py](https://github.com/CIRCL/AIL-framework/blob/master/bin/RegexForTermsFrequency.py)) to prevent module to spend hours on a single paste

If it is merged, we will import regexes defined in ``config/regex.cfg`` into redis, so that you can have multiple access point for this information.

**Comment by mokaddem** [comment]
Thanks again for the effort you put in this contribution.
However as the **merged** PR #287 includes this feature along with an integration with the web interface, I'll close this PR.
Feel free to open new issues with other ideas or improvements.
Cheers!

**Comment by xme** [comment]
Just performed a git pull + reconfigured my tags…
Good job!

/x

--
"If the enemy leaves a door open, you must rush in." - Sun Tzu
PGP Key: https://keybase.io/xme/key.asc

**Pull request closed without merging**
