### PR TITLE
Handling of multiple feeders

### PR DESCRIPTION
**Pull request by mokaddem**
## Modifications
- Modified helper.py to handle multiple zmq feeds
- Created the Mixer.py module which can run in 2 operations modes
	- operation_mode 1: Avoid any duplicates from any sources
	- operation_mode 2: Relay duplicates coming from different sources
	- It could also be used to preprocess the feed before relaying it
- Improved dashboard layout and scripts
- Fixed some small bugs and dependencies

## Note
- The name of the feed must be appened (with '>') to the paste's name: e.g. feeder1>paste_name. If the feed has no name, it's set unnamed by default.

### CODE REVIEW

**Comment by adulau** [comment]
Looks very nice. I'll make some tests and merge it later. Thanks a lot.

**Comment by mokaddem** [comment]
This is what it looks like on my computer. If there are any remarks or suggestions, do not hesitate to let me know! ;)

screenshot from 2016-12-26 16-01-25

**Comment by xme** [comment]
At the moment, I just have the CIRCL ZMQ feed and I have "unnamed_feeder" in the dashboard
I see in the code:
```
#feeder_name = ( complete_paste.replace("archive/","") ).split("/")[0]
feeder_name, paste_name = complete_paste.split('>>')
```
What's the meaning of this '>>' as separator?

**Comment by Terrtia** [comment]
hey @xme !

You can create your own feed with this separator:    feeder_name>>paste_name
Currentlty the CIRCL ZMQ feed doesn't use this separator

**Comment by xme** [comment]
Tx Aurélien,
I'll have a look as I'm considering adding more feeds like Tweets...

**Pull request merged**
